### ISSUE TITLE
move_base error

### ISSUE THREAD

**Issue by radhasaraf** [surabhi96/Library-navigating-robot#13]
On setting the 'inflation radius'(a parameter found in costmap_common_params.yaml file) as zero the gmapping node was giving a 'move_base' error. This error got resolved upon restoring the inflation radius to a value greater than zero.

**Comment by sakshikakde** [comment]
This is because of the 'inflation radius' parameter.
Make sure that the value of inflation radius is not zero.
This parameter is in costmap_common_params.yaml file.The .yaml file can be found at /home/sakshi/turtlebot/src/turtlebot_apps/turtlebot_navigation/param.
