### ISSUE TITLE
ssh rviz: cannot connect to X server

### ISSUE THREAD

**Issue by surabhi96** [surabhi96/Library-navigating-robot#2]
The main problem was we were unable to access rviz on our remote desktop. I wanted to open rviz on the host system after connecting it via ssh. For which I had entered the following commands.
$ssh sakshi@192.168.1.125
entered password
$rosrun rviz rviz
error: rviz: cannot connect to X server
Solution:
$ssh -X sakshi@192.168.1.125
This works!!

**Comment by sakshikakde** [comment]
ssh -X allows you to forward display that uses GUI through remote SSH connection.Users get the ability to bypass file permissions on the remote host (for the user's X authorization database) can access the local X11 display.
For more details,
run 'man ssh'
