### ISSUE TITLE
Cannot run roslaunch command using ssh.

### ISSUE THREAD

**Issue by sakshikakde** [surabhi96/Library-navigating-robot#24]

**Comment by surabhi96** [comment]
It seems .bashrc is not loaded (as bash is not started). So any source lines in there are not executed.
Also, it is observed that only one workspace can be sourced at a time i.e only the workspace sourced at the end of .bashrc is actually getting sourced, irrespective of the sourced workspaces lines above it.

**Comment by surabhi96** [comment]
If I run `source /opt/ros/indigo/setup.bash` in the remote terminal after connecting via ssh then the roslaunch commands works
If I want to run turtlebot specific command which requires loading the files from turtlebot package then it is needed to source turtlebot ws `source ~/turtlebot/devel/setup.bash`
