### ISSUE TITLE
Showing errror:[ERROR] [1388762076.282169241]: Skipping XML Document "/opt/ros/indigo/share/gmapping/nodelet_plugins.xml" which had no Root Element.  This likely means the XML is malformed or missing.

### ISSUE THREAD

**Issue by sakshikakde** [surabhi96/Library-navigating-robot#3]

**Comment by sakshikakde** [comment]
The error says,XML missing or malformed.
This can be solved by coping the file nodelet_plugins.xml to the location /opt/ros/indigo/share/gmapping.
However,the coping shall be done as root user.
Follow the instructions:
1)Find location of nodelet_plugins.xml by using command 'locate nodelet_plugins.xml'
2)Copy the file to desired location.
sudo cp -R /path/to/files/you/want/copied/ /copy/to/this/path/
eg:-sudo cp -R /opt/ros/indigo/share/stereo_image_proc/nodelet_plugins.xml  /opt/ros/indigo/share/gmapping.

This should solve your error!

**Comment by lykhahaha** [comment]
@sakshikakde However, the XML（nodelet_plugins.xml ） in each folder is not the same one. I think we should search for XML files associated with gmapping.
such as :gmapping/slam_gmapping/gmapping/nodelet_plugins.xml

**Comment by githublyk** [comment]
@sakshikakde  However，the XML file (nodelet_plugins.xml ) in each floder is not the same one. The xml file in the gmapping is different ,so wo should search the xml file related to the gmapping and copy it to the gmapping floder.
